wscl-issues: Add more current practices
s-expressionists/wscl pull request #11
Opened 2021-09-18 14:51 UTC by yitzchak

Also fix a small typo in the test case of the clrhash-type-error issue.

2021-09-21 23:12 UTC, scymtym requested changes
One very minor issue in a commit comment.

2021-09-21 23:12 UTC, scymtym commented on wscl-issues/proposed/find-package-type-error
> +                   (OR CHARACTER PACKAGE STRING SYMBOL)]
Indentation looks wrong here.

2021-09-21 23:24 UTC, yitzchak commented on wscl-issues/proposed/find-package-type-error
> +                   (OR CHARACTER PACKAGE STRING SYMBOL)]
Fixed.

2021-09-22 11:09 UTC, scymtym approved these changes

2021-09-22 11:09 UTC, scymtym commented
Looks good to me, thanks.

2021-09-22 11:09 UTC, merged